"""
This type stub file was generated by pyright.
"""

import json
from django.core.serializers.python import Deserializer as PythonDeserializer, Serializer as PythonSerializer

"""
Serialize data to/from JSON
"""
class Serializer(PythonSerializer):
    """Convert a queryset to JSON."""
    internal_use_only = ...
    def start_serialization(self) -> None:
        ...
    
    def end_serialization(self) -> None:
        ...
    
    def end_object(self, obj) -> None:
        ...
    
    def getvalue(self) -> str | None:
        ...
    


class Deserializer(PythonDeserializer):
    """Deserialize a stream or string of JSON data."""
    def __init__(self, stream_or_string, **options) -> None:
        ...
    


class DjangoJSONEncoder(json.JSONEncoder):
    """
    JSONEncoder subclass that knows how to encode date/time, decimal types, and
    UUIDs.
    """
    def default(self, o) -> str | Any:
        ...
    


