"""
This type stub file was generated by pyright.
"""

from django.db.models import Field
from django.utils.functional import cached_property

class AttributeSetter:
    def __init__(self, name, value) -> None:
        ...
    


class CompositeAttribute:
    def __init__(self, field) -> None:
        ...
    
    @property
    def attnames(self) -> list[Any]:
        ...
    
    def __get__(self, instance, cls=...) -> tuple[Any, ...]:
        ...
    
    def __set__(self, instance, values) -> None:
        ...
    


class CompositePrimaryKey(Field):
    descriptor_class = CompositeAttribute
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def deconstruct(self) -> tuple[Any | None, str, tuple[Any, ...], dict[Any, Any]]:
        ...
    
    @cached_property
    def fields(self) -> tuple[Any, ...]:
        ...
    
    @cached_property
    def columns(self) -> tuple[Any, ...]:
        ...
    
    def contribute_to_class(self, cls, name, private_only=...) -> None:
        ...
    
    def get_attname_column(self) -> tuple[Any | None, None]:
        ...
    
    def __iter__(self):
        ...
    
    def __len__(self) -> int:
        ...
    
    @cached_property
    def cached_col(self) -> ColPairs:
        ...
    
    def get_col(self, alias, output_field=...) -> cached_property | ColPairs:
        ...
    
    def get_pk_value_on_save(self, instance) -> tuple[Any, ...]:
        ...
    
    def value_to_string(self, obj) -> str:
        ...
    
    def to_python(self, value) -> list[Any]:
        ...
    


def unnest(fields) -> list[Any]:
    ...

