"""
This type stub file was generated by pyright.
"""

from django.db.models.lookups import Exact, GreaterThan, GreaterThanOrEqual, In, IsNull, LessThan, LessThanOrEqual

def get_normalized_value(value, lhs) -> tuple[Any, ...] | tuple[Any]:
    ...

class RelatedIn(In):
    def get_prep_lookup(self) -> ExpressionList | list[Any]:
        ...
    
    def as_sql(self, compiler, connection) -> tuple[str, list[Any]] | tuple[LiteralString, list[Any]]:
        ...
    


class RelatedLookupMixin:
    def get_prep_lookup(self):
        ...
    
    def as_sql(self, compiler, connection):
        ...
    


class RelatedExact(RelatedLookupMixin, Exact):
    ...


class RelatedLessThan(RelatedLookupMixin, LessThan):
    ...


class RelatedGreaterThan(RelatedLookupMixin, GreaterThan):
    ...


class RelatedGreaterThanOrEqual(RelatedLookupMixin, GreaterThanOrEqual):
    ...


class RelatedLessThanOrEqual(RelatedLookupMixin, LessThanOrEqual):
    ...


class RelatedIsNull(RelatedLookupMixin, IsNull):
    ...


