"""
This type stub file was generated by pyright.
"""

from django.db.models.expressions import Func
from django.db.models.lookups import Exact, GreaterThan, GreaterThanOrEqual, In, IsNull, LessThan, LessThanOrEqual

class Tuple(Func):
    allows_composite_expressions = ...
    function = ...
    output_field = ...
    def __len__(self) -> int:
        ...
    
    def __iter__(self) -> Iterator[Any | F | Value]:
        ...
    


class TupleLookupMixin:
    allows_composite_expressions = ...
    def get_prep_lookup(self):
        ...
    
    def check_rhs_is_tuple_or_list(self) -> None:
        ...
    
    def check_rhs_length_equals_lhs_length(self) -> None:
        ...
    
    def check_rhs_is_supported_expression(self) -> None:
        ...
    
    def get_lhs_str(self) -> str:
        ...
    
    def get_prep_lhs(self) -> Tuple:
        ...
    
    def process_lhs(self, compiler, connection, lhs=...) -> tuple[str | Any, Any]:
        ...
    
    def process_rhs(self, compiler, connection) -> tuple[Any, Any]:
        ...
    
    def get_fallback_sql(self, compiler, connection):
        ...
    
    def as_sql(self, compiler, connection):
        ...
    


class TupleExact(TupleLookupMixin, Exact):
    def get_fallback_sql(self, compiler, connection) -> tuple[Any, list[Any]] | tuple[LiteralString, list[Any]] | tuple[str | Any, list[Any]]:
        ...
    


class TupleIsNull(TupleLookupMixin, IsNull):
    def get_prep_lookup(self) -> bool:
        ...
    
    def as_sql(self, compiler, connection) -> tuple[str | Any, list[Any]]:
        ...
    


class TupleGreaterThan(TupleLookupMixin, GreaterThan):
    def get_fallback_sql(self, compiler, connection) -> tuple[str | Any, list[Any]]:
        ...
    


class TupleGreaterThanOrEqual(TupleLookupMixin, GreaterThanOrEqual):
    def get_fallback_sql(self, compiler, connection) -> tuple[str | Any, list[Any]]:
        ...
    


class TupleLessThan(TupleLookupMixin, LessThan):
    def get_fallback_sql(self, compiler, connection) -> tuple[str | Any, list[Any]]:
        ...
    


class TupleLessThanOrEqual(TupleLookupMixin, LessThanOrEqual):
    def get_fallback_sql(self, compiler, connection) -> tuple[str | Any, list[Any]]:
        ...
    


class TupleIn(TupleLookupMixin, In):
    def get_prep_lookup(self) -> Any | Value:
        ...
    
    def check_rhs_is_collection_of_tuples_or_lists(self) -> None:
        ...
    
    def check_rhs_elements_length_equals_lhs_length(self) -> None:
        ...
    
    def check_rhs_is_query(self) -> None:
        ...
    
    def process_rhs(self, compiler, connection) -> tuple[LiteralString, tuple[Any, ...]] | tuple[tuple[Any, ...], tuple[Any, ...]]:
        ...
    
    def get_fallback_sql(self, compiler, connection) -> tuple[str, list[Any]] | tuple[LiteralString, list[Any]] | tuple[str | Any, list[Any]]:
        ...
    


tuple_lookups = ...
