"""
This type stub file was generated by pyright.
"""

from django.core.checks import Tags, register

@register(Tags.commands)
def migrate_and_makemigrations_autodetector(**kwargs) -> list[Error] | list[Any]:
    ...

