"""
This type stub file was generated by pyright.
"""

from django.core.management.base import BaseCommand

class TemplateCommand(BaseCommand):
    """
    Copy either a Django application layout template or a Django project
    layout template into the specified directory.

    :param style: A color style object (see django.core.management.color).
    :param app_or_project: The string 'app' or 'project'.
    :param name: The name of the application or project.
    :param directory: The directory to which the template should be copied.
    :param options: The additional variables passed to project or app templates
    """
    requires_system_checks = ...
    url_schemes = ...
    rewrite_template_suffixes = ...
    def add_arguments(self, parser) -> None:
        ...
    
    def handle(self, app_or_project, name, target=..., **options) -> None:
        ...
    
    def handle_template(self, template, subdir) -> str:
        """
        Determine where the app or project templates are.
        Use django.__path__[0] as the default because the Django install
        directory isn't known.
        """
        ...
    
    def validate_name(self, name, name_or_dir=...) -> None:
        ...
    
    def download(self, url) -> str:
        """
        Download the given URL and return the file name.
        """
        ...
    
    def splitext(self, the_path) -> tuple[Any, Any]:
        """
        Like os.path.splitext, but takes off .tar, too
        """
        ...
    
    def extract(self, filename) -> str:
        """
        Extract the given file to a temporary directory and return
        the path of the directory with the extracted content.
        """
        ...
    
    def is_url(self, template) -> bool:
        """Return True if the name looks like a URL."""
        ...
    
    def apply_umask(self, old_path, new_path) -> None:
        ...
    
    def make_writeable(self, filename) -> None:
        """
        Make sure that the file is writeable.
        Useful if our source is read-only.
        """
        ...
    


