"""
This type stub file was generated by pyright.
"""

def popen_wrapper(args, stdout_encoding=...) -> tuple[str, str, int]:
    """
    Friendly wrapper around Popen.

    Return stdout output, stderr output, and OS status code.
    """
    ...

def handle_extensions(extensions) -> set[Any]:
    """
    Organize multiple extensions that are separated with commas or passed by
    using --extension/-e multiple times.

    For example: running 'django-admin makemessages -e js,txt -e xhtml -a'
    would result in an extension list: ['.js', '.txt', '.xhtml']

    >>> handle_extensions(['.html', 'html,js,py,py,py,.py', 'py,.py'])
    {'.html', '.js', '.py'}
    >>> handle_extensions(['.html, txt,.tpl'])
    {'.html', '.tpl', '.txt'}
    """
    ...

def find_command(cmd, path=..., pathext=...) -> str | None:
    ...

def get_random_secret_key() -> str:
    """
    Return a 50 character random string usable as a SECRET_KEY setting value.
    """
    ...

def parse_apps_and_model_labels(labels) -> tuple[set[Any], set[Any]]:
    """
    Parse a list of "app_label.ModelName" or "app_label" strings into actual
    objects and return a two-element tuple:
        (set of model classes, set of app_configs).
    Raise a CommandError if some specified models or apps don't exist.
    """
    ...

def get_command_line_option(argv, option) -> Any | None:
    """
    Return the value of a command line option (which should include leading
    dashes, e.g. '--testrunner') from an argument list. Return None if the
    option wasn't passed or if the argument list couldn't be parsed.
    """
    ...

def normalize_path_patterns(patterns) -> list[Any]:
    """Normalize an iterable of glob style patterns based on OS."""
    ...

def is_ignored_path(path, ignore_patterns) -> bool:
    """
    Check if the given path should be ignored or not based on matching
    one of the glob style `ignore_patterns`.
    """
    ...

def find_formatters() -> dict[str, str | None]:
    ...

def run_formatters(written_files, black_path=..., stderr=...) -> None:
    """
    Run the black formatter on the specified files.
    """
    ...

