"""
This type stub file was generated by pyright.
"""

def makedirs(name, mode=..., exist_ok=..., *, parent_mode=...) -> None:
    """makedirs(name [, mode=0o777][, exist_ok=False][, parent_mode=None])

    Super-mkdir; create a leaf directory and all intermediate ones.  Works like
    mkdir, except that any intermediate path segment (not just the rightmost)
    will be created if it does not exist. If the target directory already
    exists, raise an OSError if exist_ok is False. Otherwise no exception is
    raised.  If parent_mode is not None, it will be used as the mode for any
    newly-created, intermediate-level directories. Otherwise, intermediate
    directories are created with the default permissions (respecting umask).
    This is recursive.

    """
    ...

def safe_makedirs(name, mode=..., exist_ok=...) -> None:
    """Create directories recursively with explicit `mode` on each level."""
    ...

def safe_join(base, *paths):
    """
    Join one or more path components to the base path component intelligently.
    Return a normalized, absolute version of the final path.

    Raise SuspiciousFileOperation if the final path isn't located inside of the
    base path component.
    """
    ...

def symlinks_supported() -> bool:
    """
    Return whether or not creating symlinks are supported in the host platform
    and/or if they are allowed to be created (e.g. on Windows it requires admin
    permissions).
    """
    ...

def to_path(value) -> Path:
    """Convert value to a pathlib.Path instance, if not already a Path."""
    ...

