"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from django.utils.version import PY314

if PY314:
    lock = ...
    safe_signature_from_callable = ...
ARG_KINDS = ...
def get_func_args(func) -> list[str]:
    ...

def get_func_full_args(func) -> list[Any]:
    """
    Return a list of (argument name, default value) tuples. If the argument
    does not have a default value, omit it in the tuple. Arguments such as
    *args and **kwargs are also included.
    """
    ...

def func_accepts_kwargs(func) -> bool:
    """Return True if function 'func' accepts keyword arguments **kwargs."""
    ...

def func_accepts_var_args(func) -> bool:
    """
    Return True if function 'func' accepts positional arguments *args.
    """
    ...

def method_has_no_args(meth) -> bool:
    """Return True if a method only accepts 'self'."""
    ...

def func_supports_parameter(func, name) -> bool:
    ...

@contextmanager
def lazy_annotations() -> Generator[None, Any, None]:
    """
    inspect.getfullargspec eagerly evaluates type annotations. To add
    compatibility with Python 3.14+ deferred evaluation, patch the module-level
    helper to provide the annotation_format that we are using elsewhere.

    This private helper could be removed when there is an upstream solution for
    https://github.com/python/cpython/issues/141560.

    This context manager is not reentrant.
    """
    ...

def signature(obj) -> Signature:
    """
    A wrapper around inspect.signature that leaves deferred annotations
    unevaluated on Python 3.14+, since they are not used in our case.
    """
    ...

